export const LIST = {
  total: 18,
  objectIDs: [
    848290, 691091, 778803, 839361, 208967, 436180, 435821, 60451, 857221,
    857222, 437449, 839021, 857478, 437489, 503341, 436883, 436105, 436283,
  ],
};

export const RESULTS = [
  {
    objectID: 848290,
    isHighlight: false,
    accessionNumber: "2022.123",
    accessionYear: "2022",
    isPublicDomain: false,
    primaryImage: "",
    primaryImageSmall: "",
    additionalImages: [],
    constituents: [
      {
        constituentID: 214953,
        role: "Artist",
        name: "Sosa Joseph",
        constituentULAN_URL: "(not assigned)",
        constituentWikidata_URL: "https://www.wikidata.org/wiki/Q5765403",
        gender: "",
      },
    ],
    department: "Modern and Contemporary Art",
    objectName: "Painting",
    title: "What are we? III",
    culture: "",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Artist",
    artistPrefix: "",
    artistDisplayName: "Sosa Joseph",
    artistDisplayBio: "Indian, born Parumala 1971",
    artistSuffix: "",
    artistAlphaSort: "Joseph, Sosa",
    artistNationality: "Indian",
    artistBeginDate: "1971",
    artistEndDate: "9999",
    artistGender: "",
    artistWikidata_URL: "https://www.wikidata.org/wiki/Q5765403",
    artistULAN_URL: "(not assigned)",
    objectDate: "2012",
    objectBeginDate: 2012,
    objectEndDate: 2012,
    medium: "Oil on canvas",
    dimensions: "56 in. × 12 ft. 2 in. (142.2 × 370.8 cm)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Height: 142.24028,
          Width: 370.84073,
        },
      },
    ],
    creditLine:
      "Purchase, Estate of Howard Hodgkin Gift and funds from various donors, 2022",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Paintings",
    rightsAndReproduction: "Copyright Sosa Joseph, 2012, All rights reserved",
    linkResource: "",
    metadataDate: "2023-02-07T04:46:51.34Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/848290",
    tags: null,
    objectWikidata_URL: "https://www.wikidata.org/wiki/Q116445543",
    isTimelineWork: false,
    GalleryNumber: "915",
  },
  {
    message: "Not a valid object",
  },
  {
    objectID: 778803,
    isHighlight: false,
    accessionNumber: "2019.338a–d",
    accessionYear: "2019",
    isPublicDomain: false,
    primaryImage: "",
    primaryImageSmall: "",
    additionalImages: [],
    constituents: [
      {
        constituentID: 203205,
        role: "Design House",
        name: "Vaquera",
        constituentULAN_URL: "",
        constituentWikidata_URL: "",
        gender: "",
      },
      {
        constituentID: 203205,
        role: "Designer",
        name: "Patric DiCaprio, born Mobile, Alabama, 1990",
        constituentULAN_URL: "",
        constituentWikidata_URL: "",
        gender: "",
      },
      {
        constituentID: 203205,
        role: "Designer",
        name: "Bryn Taubensee, born Bloomington, Indiana, 1989",
        constituentULAN_URL: "",
        constituentWikidata_URL: "",
        gender: "",
      },
      {
        constituentID: 203205,
        role: "Designer",
        name: "Claire Sullivan, born Richmond, Virginia, 1993",
        constituentULAN_URL: "",
        constituentWikidata_URL: "",
        gender: "",
      },
    ],
    department: "Costume Institute",
    objectName: "Ensemble",
    title: "Ensemble",
    culture: "American",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Design House",
    artistPrefix: "",
    artistDisplayName: "Vaquera",
    artistDisplayBio: "American, founded 2016",
    artistSuffix: "",
    artistAlphaSort: "Vaquera",
    artistNationality: "American",
    artistBeginDate: "2016",
    artistEndDate: "",
    artistGender: "",
    artistWikidata_URL: "",
    artistULAN_URL: "",
    objectDate: "fall/winter 2017–18",
    objectBeginDate: 2017,
    objectEndDate: 2018,
    medium: "(a, b) synthetic fiber, (c, d) synthetic suede, acrylic paint",
    dimensions: "",
    measurements: [
      {
        elementName: "Length at CF",
        elementDescription: null,
        elementMeasurements: {
          Length: 68.58014,
        },
      },
    ],
    creditLine: "Purchase, The Dorothy Strelsin Foundation Inc. Gift, 2019",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2023-06-15T04:55:04.637Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/778803",
    tags: null,
    objectWikidata_URL: "",
    isTimelineWork: false,
    GalleryNumber: "",
  },
  {
    objectID: 839361,
    isHighlight: false,
    accessionNumber: "2019.471",
    accessionYear: "2019",
    isPublicDomain: false,
    primaryImage: "",
    primaryImageSmall: "",
    additionalImages: [],
    constituents: [
      {
        constituentID: 162421,
        role: "Artist",
        name: "Lorna Simpson",
        constituentULAN_URL: "http://vocab.getty.edu/page/ulan/500088695",
        constituentWikidata_URL: "https://www.wikidata.org/wiki/Q6681389",
        gender: "Female",
      },
    ],
    department: "Modern and Contemporary Art",
    objectName: "Collage",
    title: "Earth & Sky",
    culture: "",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Artist",
    artistPrefix: "",
    artistDisplayName: "Lorna Simpson",
    artistDisplayBio: "American, born Brooklyn, New York, 1960",
    artistSuffix: "",
    artistAlphaSort: "Simpson, Lorna",
    artistNationality: "American",
    artistBeginDate: "1960",
    artistEndDate: "9999",
    artistGender: "Female",
    artistWikidata_URL: "https://www.wikidata.org/wiki/Q6681389",
    artistULAN_URL: "http://vocab.getty.edu/page/ulan/500088695",
    objectDate: "2018",
    objectBeginDate: 2018,
    objectEndDate: 2018,
    medium: "Cut and pasted printed papers",
    dimensions: "11 in. × 8 1/2 in. (27.9 × 21.6 cm)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Height: 27.940056,
          Width: 21.590044,
        },
      },
      {
        elementName: "Frame",
        elementDescription: "Standard walnut frame with AR plexi",
        elementMeasurements: {
          Depth: 3.8100076,
          "Face Width": 0.9525019,
          Height: 51.435104,
          Width: 38.735077,
        },
      },
    ],
    creditLine: "Gift of Dodie Kazanjian and Calvin Tomkins, 2019",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Works on Paper",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2023-01-09T12:29:55.66Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/839361",
    tags: null,
    objectWikidata_URL: "https://www.wikidata.org/wiki/Q96358180",
    isTimelineWork: false,
    GalleryNumber: "",
  },
  {
    objectID: 208967,
    isHighlight: false,
    accessionNumber: "57.108.19",
    accessionYear: "1957",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/es/original/163817.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/es/web-large/163817.jpg",
    additionalImages: [
      "https://images.metmuseum.org/CRDImages/es/original/237307.jpg",
      "https://images.metmuseum.org/CRDImages/es/original/237308.jpg",
    ],
    constituents: null,
    department: "European Sculpture and Decorative Arts",
    objectName: "Tobacco box",
    title: "Tobacco box",
    culture: "",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "",
    artistPrefix: "",
    artistDisplayName: "",
    artistDisplayBio: "",
    artistSuffix: "",
    artistAlphaSort: "",
    artistNationality: "",
    artistBeginDate: "",
    artistEndDate: "",
    artistGender: "",
    artistWikidata_URL: "",
    artistULAN_URL: "",
    objectDate: "ca. 1734",
    objectBeginDate: 1729,
    objectEndDate: 1739,
    medium: "Copper",
    dimensions: "Overall: 1 1/4 × 5 3/16 × 2 1/4 in. (3.2 × 13.2 × 5.7 cm)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Depth: 5.7,
          Height: 3.2,
          Width: 13.2,
        },
      },
    ],
    creditLine:
      "Gift of C. Gustave Mourraille, in memory of his sister, Miss M. Mathilde Mourraille, 1957",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Metalwork-Copper",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2020-09-16T18:35:19.457Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/208967",
    tags: [
      {
        term: "Men",
        AAT_URL: "http://vocab.getty.edu/page/aat/300025928",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q8441",
      },
      {
        term: "Women",
        AAT_URL: "http://vocab.getty.edu/page/aat/300025943",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q467",
      },
      {
        term: "Coat of Arms",
        AAT_URL: "http://vocab.getty.edu/page/aat/300126352",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q14659",
      },
    ],
    objectWikidata_URL: "",
    isTimelineWork: false,
    GalleryNumber: "",
  },
  {
    objectID: 436180,
    isHighlight: false,
    accessionNumber: "1989.328",
    accessionYear: "1989",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ep/original/DP-14345-001.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ep/web-large/DP-14345-001.jpg",
    additionalImages: [],
    constituents: [
      {
        constituentID: 161823,
        role: "Artist",
        name: "Eugène Delacroix",
        constituentULAN_URL: "http://vocab.getty.edu/page/ulan/500115509",
        constituentWikidata_URL: "https://www.wikidata.org/wiki/Q33477",
        gender: "",
      },
    ],
    department: "European Paintings",
    objectName: "Painting",
    title: "The Natchez",
    culture: "",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Artist",
    artistPrefix: "",
    artistDisplayName: "Eugène Delacroix",
    artistDisplayBio: "French, Charenton-Saint-Maurice 1798–1863 Paris",
    artistSuffix: "",
    artistAlphaSort: "Delacroix, Eugène",
    artistNationality: "French",
    artistBeginDate: "1798",
    artistEndDate: "1863",
    artistGender: "",
    artistWikidata_URL: "https://www.wikidata.org/wiki/Q33477",
    artistULAN_URL: "http://vocab.getty.edu/page/ulan/500115509",
    objectDate: "1823–24 and 1835",
    objectBeginDate: 1823,
    objectEndDate: 1835,
    medium: "Oil on canvas",
    dimensions: "35 1/2 x 46 in. (90.2 x 116.8 cm)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Height: 90.2,
          Width: 116.8,
        },
      },
      {
        elementName: "Frame",
        elementDescription: null,
        elementMeasurements: {
          Depth: 16.827534,
          Height: 130.17526,
          Width: 156.8453,
        },
      },
    ],
    creditLine:
      "Purchase, Gifts of George N. and Helen M. Richard and Mr. and Mrs. Charles S. McVeigh and Bequest of Emma A. Sheafer, by exchange, 1989",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Paintings",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2023-06-03T04:54:36.733Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/436180",
    tags: [
      {
        term: "Infants",
        AAT_URL: "http://vocab.getty.edu/page/aat/300189561",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q998",
      },
      {
        term: "Fathers",
        AAT_URL: "http://vocab.getty.edu/page/aat/300025931",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q7565",
      },
      {
        term: "Mothers",
        AAT_URL: "http://vocab.getty.edu/page/aat/300025932",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q7560",
      },
      {
        term: "Family",
        AAT_URL: "http://vocab.getty.edu/page/aat/300435378",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q8436",
      },
    ],
    objectWikidata_URL: "https://www.wikidata.org/wiki/Q19911558",
    isTimelineWork: true,
    GalleryNumber: "801",
  },
  {
    objectID: 435821,
    isHighlight: false,
    accessionNumber: "95.14.81",
    accessionYear: "1895",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ep/original/DT345086.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ep/web-large/DT345086.jpg",
    additionalImages: [],
    constituents: [
      {
        constituentID: 163330,
        role: "Artist",
        name: "Adam Buck",
        constituentULAN_URL: "http://vocab.getty.edu/page/ulan/500031258",
        constituentWikidata_URL: "https://www.wikidata.org/wiki/Q4678798",
        gender: "",
      },
    ],
    department: "European Paintings",
    objectName: "Painting, miniature",
    title: "Portrait of a Woman, Said to Be Emma (1765–1815), Lady Hamilton",
    culture: "",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Artist",
    artistPrefix: "",
    artistDisplayName: "Adam Buck",
    artistDisplayBio: "Irish, Cork 1759–1833 London",
    artistSuffix: "",
    artistAlphaSort: "Buck, Adam",
    artistNationality: "Irish",
    artistBeginDate: "1759",
    artistEndDate: "1833",
    artistGender: "",
    artistWikidata_URL: "https://www.wikidata.org/wiki/Q4678798",
    artistULAN_URL: "http://vocab.getty.edu/page/ulan/500031258",
    objectDate: "1804",
    objectBeginDate: 1804,
    objectEndDate: 1804,
    medium: "Ivory",
    dimensions: "Diameter 1 1/4 in. (32 mm)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Height: 3.2,
          Width: 3.2,
        },
      },
    ],
    creditLine:
      "The Moses Lazarus Collection, Gift of Josephine and Sarah Lazarus, in memory of their father, 1888–95",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Miniatures",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2020-09-16T18:35:19.457Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/435821",
    tags: [
      {
        term: "Pendants",
        AAT_URL: "http://vocab.getty.edu/page/aat/300046002",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q2111434",
      },
      {
        term: "Profiles",
        AAT_URL: "http://vocab.getty.edu/page/aat/300123319",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q4382010",
      },
      {
        term: "Women",
        AAT_URL: "http://vocab.getty.edu/page/aat/300025943",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q467",
      },
    ],
    objectWikidata_URL: "https://www.wikidata.org/wiki/Q19913980",
    isTimelineWork: false,
    GalleryNumber: "",
  },
  {
    objectID: 60451,
    isHighlight: false,
    accessionNumber: "2014.719.5",
    accessionYear: "2014",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/as/original/DP298302.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/as/web-large/DP298302.jpg",
    additionalImages: [
      "https://images.metmuseum.org/CRDImages/as/original/DP298253.jpg",
      "https://images.metmuseum.org/CRDImages/as/original/SC-2014_719_5-001.jpg",
      "https://images.metmuseum.org/CRDImages/as/original/SC-2014_719_5-002.jpg",
      "https://images.metmuseum.org/CRDImages/as/original/SC-2014_719_5-003a.jpg",
      "https://images.metmuseum.org/CRDImages/as/original/SC-2014_719_5-003b.jpg",
      "https://images.metmuseum.org/CRDImages/as/original/SC-2014_719_5-003c(F).jpg",
      "https://images.metmuseum.org/CRDImages/as/original/SC-2014_719_5-003c(B).jpg",
      "https://images.metmuseum.org/CRDImages/as/original/SC-2014_719_5-004.jpg",
      "https://images.metmuseum.org/CRDImages/as/original/SC-2014_719_5-005.jpg",
    ],
    constituents: [
      {
        constituentID: 13422,
        role: "Artist",
        name: "Myōe Kōben 明恵高弁",
        constituentULAN_URL: "",
        constituentWikidata_URL: "",
        gender: "",
      },
    ],
    department: "Asian Art",
    objectName: "Hanging scroll",
    title: "Letter to the Nun Jōjūbō",
    culture: "Japan",
    period: "Kamakura period (1185–1333)",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Artist",
    artistPrefix: "",
    artistDisplayName: "Myōe Kōben 明恵高弁",
    artistDisplayBio: "Japanese, 1173–1232",
    artistSuffix: "",
    artistAlphaSort: "Myōe Kōben",
    artistNationality: "Japanese",
    artistBeginDate: "1173",
    artistEndDate: "1232",
    artistGender: "",
    artistWikidata_URL: "",
    artistULAN_URL: "",
    objectDate: "ca. 1221",
    objectBeginDate: 1221,
    objectEndDate: 1221,
    medium: "Hanging scroll; ink on paper",
    dimensions:
      "Image: 8 1/4 x 17 in. (21 x 43.2 cm)\r\nOverall with mounting: 39 7/8 x 21 1/16 in. (101.3 x 53.5 cm)\r\nOverall with knobs: 39 7/8 x 22 7/8 in. (101.3 x 58.1 cm)",
    measurements: [
      {
        elementName: "Overall with knobs",
        elementDescription: null,
        elementMeasurements: {
          Height: 101.3,
          Width: 58.1,
        },
      },
      {
        elementName: "Overall with mounting",
        elementDescription: null,
        elementMeasurements: {
          Height: 101.3,
          Width: 53.5,
        },
      },
      {
        elementName: "Image",
        elementDescription: null,
        elementMeasurements: {
          Height: 21,
          Width: 43.2,
        },
      },
    ],
    creditLine:
      "Gift of Sylvan Barnet and William Burto, in honor of Saretta and Howard Barnet, 2014",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Calligraphy",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2021-10-28T04:38:52.167Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/60451",
    tags: null,
    objectWikidata_URL: "",
    isTimelineWork: false,
    GalleryNumber: "",
  },
  {
    objectID: 857221,
    isHighlight: false,
    accessionNumber: "85.16.1",
    accessionYear: "1885",
    isPublicDomain: false,
    primaryImage: "",
    primaryImageSmall: "",
    additionalImages: [],
    constituents: [
      {
        constituentID: 218614,
        role: "Artist",
        name: "Charles L. Hogeboom",
        constituentULAN_URL: "",
        constituentWikidata_URL: "",
        gender: "",
      },
    ],
    department: "The American Wing",
    objectName: "Bust",
    title: "Benjamin Franklin",
    culture: "",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Artist",
    artistPrefix: "",
    artistDisplayName: "Charles L. Hogeboom",
    artistDisplayBio: "American",
    artistSuffix: "",
    artistAlphaSort: "Hogeboom, Charles L.",
    artistNationality: "American",
    artistBeginDate: "",
    artistEndDate: "",
    artistGender: "",
    artistWikidata_URL: "",
    artistULAN_URL: "",
    objectDate: "",
    objectBeginDate: 0,
    objectEndDate: 0,
    medium: "Plaster",
    dimensions:
      "18 11/16 × 16 1/4 × 2 3/16 in. (47.5 × 41.3 × 5.6 cm)\r\nFramed: 26 1/2 in. × 24 in. × 3 in. (67.3 × 61 × 7.6 cm)",
    measurements: [
      {
        elementName: "Framed",
        elementDescription: null,
        elementMeasurements: {
          Depth: 7.620015,
          Height: 67.310135,
          Width: 60.96012,
        },
      },
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Depth: 5.556261,
          Height: 47.466347,
          Width: 41.27508,
        },
      },
    ],
    creditLine: "Gift of the sculptor, 1885",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2023-02-23T04:47:30.613Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/857221",
    tags: null,
    objectWikidata_URL: "",
    isTimelineWork: false,
    GalleryNumber: "",
  },
  {
    objectID: 857222,
    isHighlight: false,
    accessionNumber: "85.16.2",
    accessionYear: "1885",
    isPublicDomain: false,
    primaryImage: "",
    primaryImageSmall: "",
    additionalImages: [],
    constituents: [
      {
        constituentID: 218614,
        role: "Artist",
        name: "Charles L. Hogeboom",
        constituentULAN_URL: "",
        constituentWikidata_URL: "",
        gender: "",
      },
    ],
    department: "The American Wing",
    objectName: "Bust",
    title: "Thomas Jefferson",
    culture: "",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Artist",
    artistPrefix: "",
    artistDisplayName: "Charles L. Hogeboom",
    artistDisplayBio: "American",
    artistSuffix: "",
    artistAlphaSort: "Hogeboom, Charles L.",
    artistNationality: "American",
    artistBeginDate: "",
    artistEndDate: "",
    artistGender: "",
    artistWikidata_URL: "",
    artistULAN_URL: "",
    objectDate: "",
    objectBeginDate: 0,
    objectEndDate: 0,
    medium: "Plaster",
    dimensions:
      "18 1/2 × 16 1/4 × 2 3/16 in. (47 × 41.3 × 5.6 cm)\r\nFramed: 26 3/8 × 24 3/8 × 3 1/4 in. (67 × 61.9 × 8.3 cm)",
    measurements: [
      {
        elementName: "Framed",
        elementDescription: null,
        elementMeasurements: {
          Depth: 8.255016,
          Height: 66.99264,
          Width: 61.912624,
        },
      },
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Depth: 5.556261,
          Height: 46.990093,
          Width: 41.27508,
        },
      },
    ],
    creditLine: "Gift of the sculptor, 1885",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2023-02-23T04:47:30.613Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/857222",
    tags: null,
    objectWikidata_URL: "",
    isTimelineWork: false,
    GalleryNumber: "",
  },
  {
    objectID: 437449,
    isHighlight: false,
    accessionNumber: "87.16",
    accessionYear: "1887",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ep/original/DP213052.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ep/web-large/DP213052.jpg",
    additionalImages: [
      "https://images.metmuseum.org/CRDImages/ep/original/SFBlair infrared.jpg",
      "https://images.metmuseum.org/CRDImages/ep/original/SFDP210803.jpg",
    ],
    constituents: [
      {
        constituentID: 165087,
        role: "Artist",
        name: "Sir Joshua Reynolds",
        constituentULAN_URL: "http://vocab.getty.edu/page/ulan/500004539",
        constituentWikidata_URL: "https://www.wikidata.org/wiki/Q194402",
        gender: "",
      },
    ],
    department: "European Paintings",
    objectName: "Painting",
    title:
      "The Honorable Henry Fane (1739–1802) with Inigo Jones and Charles Blair",
    culture: "",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Artist",
    artistPrefix: "",
    artistDisplayName: "Sir Joshua Reynolds",
    artistDisplayBio: "British, Plympton 1723–1792 London",
    artistSuffix: "",
    artistAlphaSort: "Reynolds, Joshua, Sir",
    artistNationality: "British",
    artistBeginDate: "1723",
    artistEndDate: "1792",
    artistGender: "",
    artistWikidata_URL: "https://www.wikidata.org/wiki/Q194402",
    artistULAN_URL: "http://vocab.getty.edu/page/ulan/500004539",
    objectDate: "1761–66",
    objectBeginDate: 1761,
    objectEndDate: 1766,
    medium: "Oil on canvas",
    dimensions: "100 1/4 x 142 in. (254.6 x 360.7 cm)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Height: 254.6,
          Weight: 181.43881,
          Width: 360.7,
        },
      },
      {
        elementName: "Frame",
        elementDescription: null,
        elementMeasurements: {
          Depth: 12.700026,
          Height: 320.67563,
          Width: 426.72086,
        },
      },
    ],
    creditLine: "Gift of Junius S. Morgan, 1887",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Paintings",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2023-03-27T04:47:05.64Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/437449",
    tags: [
      {
        term: "Men",
        AAT_URL: "http://vocab.getty.edu/page/aat/300025928",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q8441",
      },
      {
        term: "Portraits",
        AAT_URL: "http://vocab.getty.edu/page/aat/300015637",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q134307",
      },
      {
        term: "Dogs",
        AAT_URL: "http://vocab.getty.edu/page/aat/300265714",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q144",
      },
    ],
    objectWikidata_URL: "https://www.wikidata.org/wiki/Q19905281",
    isTimelineWork: true,
    GalleryNumber: "",
  },
  {
    objectID: 839021,
    isHighlight: false,
    accessionNumber: "2021.23",
    accessionYear: "2021",
    isPublicDomain: false,
    primaryImage: "",
    primaryImageSmall: "",
    additionalImages: [],
    constituents: [
      {
        constituentID: 211103,
        role: "Artist",
        name: "Jean Dréville",
        constituentULAN_URL: "(not assigned)",
        constituentWikidata_URL: "https://www.wikidata.org/wiki/Q472890",
        gender: "",
      },
    ],
    department: "Photographs",
    objectName: "Photograph",
    title: "Synthèse photo-cinématographique",
    culture: "",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Artist",
    artistPrefix: "",
    artistDisplayName: "Jean Dréville",
    artistDisplayBio: "French, 1906–1997",
    artistSuffix: "",
    artistAlphaSort: "Dréville, Jean",
    artistNationality: "French",
    artistBeginDate: "1906",
    artistEndDate: "1997",
    artistGender: "",
    artistWikidata_URL: "https://www.wikidata.org/wiki/Q472890",
    artistULAN_URL: "(not assigned)",
    objectDate: "1927",
    objectBeginDate: 1927,
    objectEndDate: 1927,
    medium: "Gelatin silver print",
    dimensions:
      "Image: 11 3/16 × 13 7/8 in. (28.4 × 35.2 cm)\r\nMount: 22 11/16 in. × 17 3/4 in. (57.6 × 45.1 cm)",
    measurements: [
      {
        elementName: "Mount",
        elementDescription: null,
        elementMeasurements: {
          Height: 57.626366,
          Width: 45.08509,
        },
      },
      {
        elementName: "Image",
        elementDescription: null,
        elementMeasurements: {
          Height: 28.4,
          Width: 35.2,
        },
      },
    ],
    creditLine: "Purchase, Alfred Stieglitz Society Gifts, 2021",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Photographs",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2022-06-02T05:11:01.083Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/839021",
    tags: null,
    objectWikidata_URL: "",
    isTimelineWork: false,
    GalleryNumber: "",
  },
  {
    objectID: 857478,
    isHighlight: false,
    accessionNumber: "2022.285",
    accessionYear: "2022",
    isPublicDomain: false,
    primaryImage: "",
    primaryImageSmall: "",
    additionalImages: [],
    constituents: [
      {
        constituentID: 169986,
        role: "Artist",
        name: "Unknown",
        constituentULAN_URL: "http://vocab.getty.edu/page/ulan/500125274",
        constituentWikidata_URL: "https://www.wikidata.org/wiki/Q24238356",
        gender: "",
      },
    ],
    department: "Photographs",
    objectName: "Photograph; Album",
    title: "Kodak Advertising Department All-bum",
    culture: "",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Artist",
    artistPrefix: "",
    artistDisplayName: "Unknown",
    artistDisplayBio: "American",
    artistSuffix: "",
    artistAlphaSort: "Unknown",
    artistNationality: "",
    artistBeginDate: "",
    artistEndDate: "",
    artistGender: "",
    artistWikidata_URL: "https://www.wikidata.org/wiki/Q24238356",
    artistULAN_URL: "http://vocab.getty.edu/page/ulan/500125274",
    objectDate: "October 3, 1940",
    objectBeginDate: 1940,
    objectEndDate: 1940,
    medium: "Gelatin silver prints",
    dimensions:
      "Images: 4 1/2 × 3 1/2 in. (11.4 × 8.9 cm) to 11 1/4 × 8 1/4 in. (28.6 × 21 cm), each\r\nOverall: 13 × 11 × 1/2 in. (33 × 28 × 1.3 cm)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Depth: 1.2700025,
          Height: 33,
          Width: 28,
        },
      },
      {
        elementName: "Image",
        elementDescription: null,
        elementMeasurements: {
          Height: 11.430023,
          Width: 8.8900175,
        },
      },
      {
        elementName: "Image",
        elementDescription: null,
        elementMeasurements: {
          Height: 28.575058,
          Width: 20.955042,
        },
      },
    ],
    creditLine: "Purchase, Alfred Stieglitz Society Gifts, 2022",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Photographs",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2022-08-30T04:52:07.343Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/857478",
    tags: null,
    objectWikidata_URL: "",
    isTimelineWork: false,
    GalleryNumber: "",
  },
  {
    objectID: 437489,
    isHighlight: false,
    accessionNumber: "22.60.58",
    accessionYear: "1922",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ep/original/DT2649.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ep/web-large/DT2649.jpg",
    additionalImages: [
      "https://images.metmuseum.org/CRDImages/ep/original/LC-22_60_58-IRR.jpg",
      "https://images.metmuseum.org/CRDImages/ep/original/LC-22_60_58-4.jpg",
      "https://images.metmuseum.org/CRDImages/ep/original/LC-22_60_58-8.jpg",
      "https://images.metmuseum.org/CRDImages/ep/original/LC-22_60_58-9.jpg",
      "https://images.metmuseum.org/CRDImages/ep/original/LC-22_60_58-10.jpg",
      "https://images.metmuseum.org/CRDImages/ep/original/LC-20_60_58-XRAY.jpg",
    ],
    constituents: [
      {
        constituentID: 165252,
        role: "Artist",
        name: "Juan de Flandes",
        constituentULAN_URL: "http://vocab.getty.edu/page/ulan/500029962",
        constituentWikidata_URL: "https://www.wikidata.org/wiki/Q512863",
        gender: "",
      },
    ],
    department: "European Paintings",
    objectName: "Painting, part of a triptych",
    title: "Christ Appearing to His Mother",
    culture: "",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Artist",
    artistPrefix: "",
    artistDisplayName: "Juan de Flandes",
    artistDisplayBio: "Netherlandish, active by 1496–died 1519 Palencia",
    artistSuffix: "",
    artistAlphaSort: "Juan de Flandes",
    artistNationality: "Netherlandish",
    artistBeginDate: "1496",
    artistEndDate: "1519",
    artistGender: "",
    artistWikidata_URL: "https://www.wikidata.org/wiki/Q512863",
    artistULAN_URL: "http://vocab.getty.edu/page/ulan/500029962",
    objectDate: "ca. 1496",
    objectBeginDate: 1491,
    objectEndDate: 1501,
    medium: "Oil on wood",
    dimensions:
      "25 x 15 in. (63.5 x 38.1 cm); painted surface 24 1/2 x 14 5/8 in. (62.2 x 37.1 cm)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Height: 63.5,
          Width: 38.1,
        },
      },
      {
        elementName: "Frame",
        elementDescription: null,
        elementMeasurements: {
          Depth: 5.715,
          Height: 68.5801,
          Width: 43.4976,
        },
      },
      {
        elementName: "Glazing",
        elementDescription: null,
        elementMeasurements: {
          Height: 63.817627,
          Width: 39.052578,
        },
      },
    ],
    creditLine: "The Bequest of Michael Dreicer, 1921",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Paintings",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2023-06-23T04:56:50.337Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/437489",
    tags: [
      {
        term: "Christ",
        AAT_URL: "http://vocab.getty.edu/page/ia/901000087",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q642420",
      },
      {
        term: "Virgin Mary",
        AAT_URL: "http://vocab.getty.edu/page/ia/901000032",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q345",
      },
      {
        term: "Interiors",
        AAT_URL: "http://vocab.getty.edu/page/aat/300391239",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q2998430",
      },
    ],
    objectWikidata_URL: "https://www.wikidata.org/wiki/Q19904794",
    isTimelineWork: true,
    GalleryNumber: "",
  },
  {
    objectID: 503341,
    isHighlight: false,
    accessionNumber: "1987.229",
    accessionYear: "1987",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/mi/original/C7372 1987.229.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/mi/web-large/C7372 1987.229.jpg",
    additionalImages: [
      "https://images.metmuseum.org/CRDImages/mi/original/251672.jpg",
      "https://images.metmuseum.org/CRDImages/mi/original/C7372 1987.229 plan.jpg",
    ],
    constituents: null,
    department: "Musical Instruments",
    objectName: "Square Piano",
    title: "Square Piano",
    culture: "American",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "",
    artistPrefix: "",
    artistDisplayName: "",
    artistDisplayBio: "",
    artistSuffix: "",
    artistAlphaSort: "",
    artistNationality: "",
    artistBeginDate: "",
    artistEndDate: "",
    artistGender: "",
    artistWikidata_URL: "",
    artistULAN_URL: "",
    objectDate: "late 18th century",
    objectBeginDate: 1767,
    objectEndDate: 1800,
    medium: "Black walnut, pine, sycamore, bone, iron, various materials",
    dimensions:
      "Case L. 54.9 cm (21-3/4 in.); W. 174.4 cm (68-3/4 in.); Depth w/o lid 17.9 cm (7-1/4 in.); Total H. 80.6 cm (31-3/4)\r\nH w/o stand 23 cm\r\nStand Height: 61 cm; 179 cm (L) ; 59 cm (D)",
    measurements: null,
    creditLine: "Rogers Fund, 1987",
    geographyType: "",
    city: "",
    state: "Pennsylvania",
    county: "",
    country: "United States",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Chordophone-Zither-struck-piano",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2022-09-28T04:55:47.413Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/503341",
    tags: null,
    objectWikidata_URL: "",
    isTimelineWork: false,
    GalleryNumber: "",
  },
  {
    objectID: 436883,
    isHighlight: false,
    accessionNumber: "05.38",
    accessionYear: "1905",
    isPublicDomain: false,
    primaryImage: "",
    primaryImageSmall: "",
    additionalImages: [],
    constituents: [
      {
        constituentID: 164244,
        role: "Artist",
        name: "Léon-Augustin Lhermitte",
        constituentULAN_URL: "http://vocab.getty.edu/page/ulan/500019500",
        constituentWikidata_URL: "https://www.wikidata.org/wiki/Q2756381",
        gender: "",
      },
    ],
    department: "European Paintings",
    objectName: "Painting",
    title: "Among the Humble",
    culture: "",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Artist",
    artistPrefix: "",
    artistDisplayName: "Léon-Augustin Lhermitte",
    artistDisplayBio: "French, Mont Saint-Père 1844–1925 Paris",
    artistSuffix: "",
    artistAlphaSort: "Lhermitte, Léon-Augustin",
    artistNationality: "French",
    artistBeginDate: "1844",
    artistEndDate: "1925",
    artistGender: "",
    artistWikidata_URL: "https://www.wikidata.org/wiki/Q2756381",
    artistULAN_URL: "http://vocab.getty.edu/page/ulan/500019500",
    objectDate: "1905",
    objectBeginDate: 1905,
    objectEndDate: 1905,
    medium: "Oil on canvas",
    dimensions: "104 3/4 x 90 in. (266.1 x 228.6 cm)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Height: 266.1,
          Width: 228.6,
        },
      },
      {
        elementName: "Frame",
        elementDescription: null,
        elementMeasurements: {
          Height: 298.7681,
          Width: 264.79553,
        },
      },
    ],
    creditLine: "Catharine Lorillard Wolfe Collection, Wolfe Fund, 1905",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Paintings",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2021-01-28T04:39:50.823Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/436883",
    tags: [
      {
        term: "Kitchens",
        AAT_URL: "http://vocab.getty.edu/page/aat/300004514",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q43164",
      },
      {
        term: "Christ",
        AAT_URL: "http://vocab.getty.edu/page/ia/901000087",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q642420",
      },
      {
        term: "Infants",
        AAT_URL: "http://vocab.getty.edu/page/aat/300189561",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q998",
      },
      {
        term: "Men",
        AAT_URL: "http://vocab.getty.edu/page/aat/300025928",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q8441",
      },
      {
        term: "Women",
        AAT_URL: "http://vocab.getty.edu/page/aat/300025943",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q467",
      },
    ],
    objectWikidata_URL: "https://www.wikidata.org/wiki/Q19912862",
    isTimelineWork: false,
    GalleryNumber: "",
  },
  {
    objectID: 436105,
    isHighlight: true,
    accessionNumber: "31.45",
    accessionYear: "1931",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ep/original/DP-13139-001.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ep/web-large/DP-13139-001.jpg",
    additionalImages: [
      "https://images.metmuseum.org/CRDImages/ep/original/LC-31_45_suppl_003.jpg",
    ],
    constituents: [
      {
        constituentID: 161811,
        role: "Artist",
        name: "Jacques Louis David",
        constituentULAN_URL: "http://vocab.getty.edu/page/ulan/500115221",
        constituentWikidata_URL: "https://www.wikidata.org/wiki/Q83155",
        gender: "",
      },
    ],
    department: "European Paintings",
    objectName: "Painting",
    title: "The Death of Socrates",
    culture: "",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Artist",
    artistPrefix: "",
    artistDisplayName: "Jacques Louis David",
    artistDisplayBio: "French, Paris 1748–1825 Brussels",
    artistSuffix: "",
    artistAlphaSort: "David, Jacques Louis",
    artistNationality: "French",
    artistBeginDate: "1748",
    artistEndDate: "1825",
    artistGender: "",
    artistWikidata_URL: "https://www.wikidata.org/wiki/Q83155",
    artistULAN_URL: "http://vocab.getty.edu/page/ulan/500115221",
    objectDate: "1787",
    objectBeginDate: 1787,
    objectEndDate: 1787,
    medium: "Oil on canvas",
    dimensions: "51 x 77 1/4 in. (129.5 x 196.2 cm)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Height: 129.5,
          Width: 196.2,
        },
      },
      {
        elementName: "Frame",
        elementDescription: null,
        elementMeasurements: {
          Depth: 14.605029,
          Height: 168.27533,
          Width: 233.68047,
        },
      },
    ],
    creditLine: "Catharine Lorillard Wolfe Collection, Wolfe Fund, 1931",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Paintings",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2023-06-06T04:54:51.337Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/436105",
    tags: [
      {
        term: "Lyres",
        AAT_URL: "http://vocab.getty.edu/page/aat/300042114",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q201129",
      },
      {
        term: "Socrates",
        AAT_URL: "http://vocab.getty.edu/page/ulan/500260248",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q913",
      },
      {
        term: "Men",
        AAT_URL: "http://vocab.getty.edu/page/aat/300025928",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q8441",
      },
    ],
    objectWikidata_URL: "https://www.wikidata.org/wiki/Q1752990",
    isTimelineWork: true,
    GalleryNumber: "",
  },
  {
    objectID: 436283,
    isHighlight: false,
    accessionNumber: "89.15.24",
    accessionYear: "1889",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ep/original/DT1484.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ep/web-large/DT1484.jpg",
    additionalImages: [],
    constituents: [
      {
        constituentID: 126920,
        role: "Artist",
        name: "Netherlandish Painter",
        constituentULAN_URL: "",
        constituentWikidata_URL: "",
        gender: "",
      },
    ],
    department: "European Paintings",
    objectName: "Painting",
    title: "Virgin and Child in a Niche",
    culture: "",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Artist",
    artistPrefix: "",
    artistDisplayName: "Netherlandish Painter",
    artistDisplayBio: "ca. 1500",
    artistSuffix: "",
    artistAlphaSort: "Netherlandish Painter",
    artistNationality: "Netherlandish",
    artistBeginDate: "",
    artistEndDate: "",
    artistGender: "",
    artistWikidata_URL: "",
    artistULAN_URL: "",
    objectDate: "ca. 1500",
    objectBeginDate: 1495,
    objectEndDate: 1505,
    medium: "Oil on wood",
    dimensions: "23 x 12 1/8 in. (58.4 x 30.8 cm)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Height: 58.4,
          Width: 30.8,
        },
      },
      {
        elementName: "Frame",
        elementDescription: null,
        elementMeasurements: {
          Depth: 5.397511,
          Height: 67.62763,
          Width: 40.00508,
        },
      },
    ],
    creditLine: "Marquand Collection, Gift of Henry G. Marquand, 1889",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Paintings",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2023-04-07T04:48:01.71Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/436283",
    tags: [
      {
        term: "Virgin Mary",
        AAT_URL: "http://vocab.getty.edu/page/ia/901000032",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q345",
      },
      {
        term: "Madonna and Child",
        AAT_URL: "http://vocab.getty.edu/page/ia/901000052",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q9309699",
      },
    ],
    objectWikidata_URL: "https://www.wikidata.org/wiki/Q20167100",
    isTimelineWork: false,
    GalleryNumber: "",
  },
];
